name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.6
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.19.0

  # firebase_messaging is removed
  # hive and path_provider are also removed as they are no longer used
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # build_runner and hive_generator are removed
  
flutter:
  uses-material-design: true
